import { Info } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="mt-4 flex items-start gap-2 rounded-lg border border-border/60 bg-secondary/40 px-3 py-2.5">
      <Info className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" />
      <p className="text-[11px] leading-relaxed text-muted-foreground">
        Generated by AI based on technical parameters. Not investment advice. Consult a
        SEBI-registered advisor.
      </p>
    </div>
  );
}
