"""init schema

Revision ID: 683420499963
Revises: 
Create Date: 2026-05-07 18:45:49.486015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '683420499963'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=True),
    sa.Column('retrieved', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('flagged', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_audit_user_ts', 'chat_audit', ['user_id', 'ts'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tickers', postgresql.ARRAY(sa.String(length=32)), nullable=True),
    sa.Column('sentiment', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_label', sa.String(length=16), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_news_published', 'news', ['published_at'], unique=False)
    op.create_index('ix_news_tickers', 'news', ['tickers'], unique=False, postgresql_using='gin')
    op.create_table('scrape_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scrape_log_recent', 'scrape_log', ['source', 'ts'], unique=False)
    op.create_table('stocks',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=False),
    sa.Column('yahoo_symbol', sa.String(length=32), nullable=True),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('market_cap_inr', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker'),
    sa.UniqueConstraint('isin')
    )
    op.create_table('prices_daily',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('delivery_qty', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'ts', 'source', name='pk_prices_daily')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices_daily')
    op.drop_table('stocks')
    op.drop_index('ix_scrape_log_recent', table_name='scrape_log')
    op.drop_table('scrape_log')
    op.drop_index('ix_news_tickers', table_name='news', postgresql_using='gin')
    op.drop_index('ix_news_published', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_chat_audit_user_ts', table_name='chat_audit')
    op.drop_table('chat_audit')
    # ### end Alembic commands ###
