"""add deals table

Revision ID: b2d187025f5d
Revises: f5741afc4c98
Create Date: 2026-05-07 23:30:58.273581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d187025f5d'
down_revision: Union[str, Sequence[str], None] = 'f5741afc4c98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('security_name', sa.Text(), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', 'client_name', 'side', 'kind', 'quantity', 'avg_price', name='uq_deals_natural')
    )
    op.create_index('ix_deals_symbol_date', 'deals', ['symbol', 'trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_deals_symbol_date', table_name='deals')
    op.drop_table('deals')
    # ### end Alembic commands ###
