"""add technicals table

Revision ID: ed8719152df6
Revises: 683420499963
Create Date: 2026-05-07 22:37:09.546760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed8719152df6'
down_revision: Union[str, Sequence[str], None] = '683420499963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technicals',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('rsi_14', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('macd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('macd_signal', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('macd_hist', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('bb_upper', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('bb_middle', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('bb_lower', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_20', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_50', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('sma_200', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ema_12', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('ema_26', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('vol_avg_20', sa.BigInteger(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'ts', name='pk_technicals')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technicals')
    # ### end Alembic commands ###
