"""add holdings table

Revision ID: f5741afc4c98
Revises: ed8719152df6
Create Date: 2026-05-07 23:11:31.238628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5741afc4c98'
down_revision: Union[str, Sequence[str], None] = 'ed8719152df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holdings',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('quarter_end', sa.Date(), nullable=False),
    sa.Column('promoter_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('public_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('employee_trust_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('xbrl_url', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('broadcast_date', sa.Date(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['stocks.ticker'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker', 'quarter_end', name='pk_holdings')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holdings')
    # ### end Alembic commands ###
